sudo: false
language: c
compiler:
  - clang

os:
  - osx
  - linux

env:
  - ARCH=x86_64
  - ARCH=i686
script:
  - make

branch:
  only:
    - master

addons:
  apt:
    package:
      - gcc-multilib
